name: BorderRulz
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.18.0
  # adobe_xd: ^0.1.4

  # google_maps_flutter: ^0.5.28+1
  # google_places_picker: ^2.1.0+2
  # place_picker: ^0.9.14
  # flutter_google_places: ^0.2.5
  # google_directions_api: ^0.5.0

  cupertino_icons: ^0.1.3

  # dependency_overrides:
  #   flutter_svg: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
